# Generated by Django 5.0.6 on 2024-10-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('percent', models.IntegerField(max_length=2)),
                ('des', models.CharField(max_length=20)),
            ],
        ),
    ]
