# Generated by Django 5.0.6 on 2024-10-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='des',
            field=models.CharField(max_length=70),
        ),
    ]
