# Generated by Django 5.0.6 on 2024-10-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_project_slug_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='description',
        ),
    ]
