# Generated by Django 5.0.6 on 2024-10-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='refer',
        ),
    ]
