# Generated by Django 5.0.6 on 2024-10-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_url_project_refer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=1)),
                ('percentage', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
