# Generated by Django 5.0.6 on 2024-10-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
