# Generated by Django 5.0.6 on 2024-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_qualification_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='icon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
