# Generated by Django 5.0.6 on 2024-10-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_qualification_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='percentage',
        ),
    ]
