# Generated by Django 5.0.6 on 2024-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_qualification_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
