# Generated by Django 5.0.6 on 2024-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_qualification_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
