# Generated by Django 5.0.6 on 2024-10-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_qualification_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='icon',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
